DATA BLOOD;
Infile '/home/u63443858/my_shared_file_links/schimiak/Blood_Type.csv' DELIMITER=',' DSD;
INPUT
BLOODTYPE $
;
PROC PRINT DATA = BLOOD;
RUN;

/* Frequency Plot */
PROC GCHART DATA = BLOOD;
	TITLE "DISTRIBUTION OF BLOOD TYPE FOR 50 PATIENTS";
	VBAR BLOODTYPE;
RUN;
QUIT;

/* Relative Frequency Plot */
PROC GCHART DATA = BLOOD;
	TITLE "DISTRIBUTION OF BLOOD TYPE FOR 50 PATIENTS";
	VBAR BLOODTYPE / TYPE = PERCENT;
RUN;
QUIT;

/* 3D Pie Chart of BloodType Distribution With AB "Exploded" */
PROC GCHART DATA = BLOOD;
	TITLE "DISTRIBUTION OF BLOOD TYPE FOR 50 PATIENTS";
	PIE3D BLOODTYPE / TYPE = PERCENT EXPLODE='AB';
RUN;
QUIT;