%LET N = 30;
%LET NUMSAMPLES = 1000;

DATA SIMEXP;
CALL STREAMINIT(123);
DO SAMPLEID = 1 TO &NUMSAMPLES;
DO i = 1 TO &N;X = RAND("Exponential");
OUTPUT;
END;
END;
RUN;

PROC UNIVARIATE DATA = SIMEXP;
HISTOGRAM X / NORMAL;
ODS SELECT HISTOGRAM;
RUN;

PROC MEANS DATA=SIMEXP NOPRINT;
BY SAMPLEID;
VAR X;
OUTPUT OUT=OUTSTATSEXP MEAN=SAMPLEMEAN;
RUN;

PROC MEANS DATA=OUTSTATSEXP N MEAN STD P5 P95;
VAR SAMPLEMEAN;
RUN;

ODS GRAPHICS ON;
PROC UNIVARIATE DATA=OUTSTATSEXP;
LABEL SAMPLEMEAN = "SAMPLE MEANs OF Exponential DATA";
HISTOGRAM SAMPLEMEAN / NORMAL; /* OVERLAY NORMAL FIT */
ODS SELECT HISTOGRAM;
RUN;